# $FreeBSD$

PORTNAME=	chrony
PKGNAMESUFFIX=	-lite

MAINTAINER=	decke@FreeBSD.org
COMMENT=	System clock synchronization client and server (lite)

MASTERDIR=	${.CURDIR}/../chrony

CONFLICTS_INSTALL=	chrony

OPTIONS_EXCLUDE=	DOCS EXAMPLES HTMLDOCS NETTLE NSS NTS

.include "${MASTERDIR}/Makefile"
