# $FreeBSD$

PORTNAME=	chrony
PKGNAMESUFFIX=	-lite

MAINTAINER=	decke@FreeBSD.org
COMMENT=	System clock synchronization client and server (lite package)

MASTERDIR=	${.CURDIR}/../chrony

CONFLICTS=	chrony-[0-9]*

OPTIONS_DEFAULT=USER

.include "${MASTERDIR}/Makefile"
